#!/usr/bin/env bash

export HIVE_HOME=/usr/local/lib/hive

export HADOOP_CLASSPATH="$HIVE_HOME/conf:$HIVE_HOME/lib/antlr-runtime-3.4.jar:$HIVE_HOME/lib/commons-dbcp-1.4.jar:$HIVE_HOME/lib/commons-pool-1.5.4.jar:$HIVE_HOME/lib/datanucleus-connectionpool-3.2.9.jar:$HIVE_HOME/lib/datanucleus-core-3.2.9.jar:$HIVE_HOME/lib/datanucleus-rdbms-3.2.9.jar:$HIVE_HOME/lib/hive-cli-1.2.1.jar:$HIVE_HOME/lib/hive-exec-1.2.1.jar:$HIVE_HOME/lib/hive-metastore-1.2.1.jar:$HIVE_HOME/lib/jdo-api-3.0.1.jar:$HIVE_HOME/lib/libfb303-0.9.2.jar:$HIVE_HOME/lib/libthrift-0.9.2.jar"

export TDCH_JAR=/home/svc_replicator_prod/tdch/1.4/lib/teradata-connector-1.4.2.jar

export LIB_JARS="$HIVE_HOME/lib/hive-cli-1.2.1.jar,$HIVE_HOME/lib/hive-exec-1.2.1.jar,$HIVE_HOME/lib/hive-metastore-1.2.1.jar,$HIVE_HOME/lib/libfb303-0.9.2.jar,$HIVE_HOME/lib/libthrift-0.9.2.jar,$HIVE_HOME/lib/jdo-api-3.0.1.jar"

yarn jar $TDCH_JAR com.teradata.connector.common.tool.ConnectorImportTool -Dmapreduce.job.queuename=public -Dmapreduce.map.output.compress=true -Dmapred.map.output.compress.codec=org.apache.hadoop.io.compress.SnappyCodec -libjars $LIB_JARS -classname com.teradata.jdbc.TeraDriver -url jdbc:teradata://tdwc/DATABASE=prod_groupondw  -username cerebroreplicator -password edw_infra_cerebro7 -jobtype hive -fileformat orcfile -method split.by.amp -nummappers 12 -targetpaths /user/grp_gdoop_edw_rep_prod/gbl -sourcetable gbl_fact_transactions -sourceconditions "collection_day_id='2015-03-09'" -targettableschema "transaction_id bigint, order_id string, parent_order_key bigint, cookie_b string, collection_date_key int, collection_day_id string, order_date_key int, order_day_id string, user_key bigint, gbl_deal_option_key bigint, deal_option_key bigint, deal_option_id string, city_key int, country_key smallint, transaction_source_key int, user_agent_key tinyint, refund_by_cs tinyint, refund_reason_key int, order_source_key int, discount_key bigint, utm_source_key string, utm_medium_key string, utm_campaign_key string, platform_key tinyint, action string, activations_flag tinyint, reactivations_flag tinyint, original_qty double, shipping_cost double, vat_amount double, discount_amount double, freight_cost double, gross_bookings_loc double, gross_revenue_loc double, net_gr_operational_loc double, net_gb_operational_loc double, amount_loc double, purchase_cnt int, resignation_amount double, refund_allowance double, created_date string, updated_date string, load_key int, ref_deal_option_id string, cost_to_user double, cost_to_groupon double, margin double, merchant_payment double, credit_card_fee double, est_3pl_shipping_cost double, co_op double, refund_amount double" 
